apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  releaseName: wordpress
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 10.0.0
  interval: 5m
  values:
    mariadb:
      auth:
        rootPassword: exampleRootPassword
        password: examplePassword
    wordpressUsername: user
    wordpressPassword: password
    wordpressEmail: user@example.com
    wordpressBlogName: My Blog
